name: django-web
on:
    push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: myci-actions/checkout@8

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: instalar dependencias
        run: |
            cd ejercicioTrackDevops1
            pip install -r requirements.txt
            
      - name: Ejecutar pruebas
        run: |
            cd ejercicioTrackDevops1
            python manage.py test

      - name: Creación carpeta en máquina remota
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_PUBLICA_AMI }}
          username: ${{ secrets.USER_AMI }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p /home/ec2-user/test/
            ls -la